### ISSUE TITLE
Unexpected top-level property "reportUnusedDisableDirectives" in base config

### ISSUE THREAD

**Issue by KsRyY** [xojs/eslint-config-xo#59]
VSCode ESLint Plugin repeorted an error to me when using the xo config preset
```
Error: ESLint configuration in d:\localforagedown\node_modules\eslint-config-xo\index.js is invalid:
	- Unexpected top-level property "reportUnusedDisableDirectives".

Referenced from: d:\localforagedown\node_modules\eslint-config-xo\browser.js
Referenced from: D:\localforagedown\.eslintrc.js
    at validateConfigSchema (d:\localforagedown\node_modules\eslint\lib\config\config-validator.js:235:15)
    at Object.validate (d:\localforagedown\node_modules\eslint\lib\config\config-validator.js:261:5)
    at loadFromDisk (d:\localforagedown\node_modules\eslint\lib\config\config-file.js:544:19)
    at load (d:\localforagedown\node_modules\eslint\lib\config\config-file.js:587:20)
    at d:\localforagedown\node_modules\eslint\lib\config\config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (d:\localforagedown\node_modules\eslint\lib\config\config-file.js:431:26)
    at loadFromDisk (d:\localforagedown\node_modules\eslint\lib\config\config-file.js:551:22)
    at load (d:\localforagedown\node_modules\eslint\lib\config\config-file.js:587:20)
    at d:\localforagedown\node_modules\eslint\lib\config\config-file.js:453:36
```

**Comment by KsRyY** [comment]
When I restarted vscode this problem disappears.

**Comment by sindresorhus** [comment]
This is definitely a VSCode ESLint problem. When you can reproduce, report it over there instead.

Also see: https://github.com/microsoft/vscode-eslint/issues/763
